import type { Metadata } from "next";
import {Space_Grotesk, Baskervville } from "next/font/google";
import "./globals.css";

const grostek = Space_Grotesk({
  variable: "--font-grostek",
  subsets: ["latin"],
});

const geistMono = Baskervville({
  variable: "--font-Baserville",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "orthoFx HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grostek.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
